// ─── MarpSlide — NestFrame Marp Slide Renderer ─────────────────
// Auto-generated by marp-integrate v1.0.0
// Generated: 2026-06-11T17:06:04.124127
//
// Renders markdown slide decks using @marp-team/marp-core.
// Detects --- dividers and renders slides inline with navigation.
//
// Usage:
//   <MarpSlide content={markdownString} />
//   <MarpSlide content={markdownString} theme="gaia" />

import React, { useState, useEffect, useCallback, useRef } from 'react';
import { Marp } from '@marp-team/marp-core';

// ─── Styles ───────────────────────────────────────────────────────

const MARP_SLIDE_STYLES = `
  .marp-slide-container {
    position: relative;
    width: 100%;
    max-width: 1280px;
    margin: 0 auto;
    background: var(--bg-default, #0d1117);
    border-radius: 8px;
    overflow: hidden;
  }

  .marp-slide-viewport {
    width: 100%;
    overflow: hidden;
    position: relative;
  }

  .marp-slide-viewport > div {
    width: 100%;
  }

  .marp-slide-viewport svg {
    width: 100%;
    height: auto;
    display: block;
  }

  .marp-slide-viewport section {
    padding: 48px;
    font-size: var(--font-base, 20px);
    line-height: 1.5;
  }

  .marp-slide-viewport h1 {
    font-size: 64px;
    margin-bottom: 32px;
    color: var(--text-primary, #c9d1d9);
  }

  .marp-slide-viewport h2 {
    font-size: 48px;
    margin-bottom: 24px;
  }

  .marp-slide-viewport p,
  .marp-slide-viewport li {
    font-size: 32px;
    line-height: 1.4;
  }

  .marp-slide-viewport pre,
  .marp-slide-viewport code {
    font-size: 24px;
    font-family: var(--font-mono, 'JetBrains Mono', 'Fira Code', monospace);
  }

  .marp-slide-viewport table {
    font-size: 24px;
    width: 100%;
    border-collapse: collapse;
  }

  .marp-slide-viewport th,
  .marp-slide-viewport td {
    padding: 12px 16px;
    border: 1px solid var(--border-default, #30363d);
  }

  /* ─── Navigation ──────────────────────────────────────────────── */

  .marp-nav {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 16px;
    padding: 16px;
    background: var(--bg-surface, #161b22);
    border-top: 1px solid var(--border-default, #30363d);
  }

  .marp-nav button {
    min-width: var(--touch-min, 48px);
    min-height: var(--touch-min, 48px);
    padding: 8px 24px;
    border: 1px solid var(--border-default, #30363d);
    border-radius: 6px;
    background: var(--bg-default, #0d1117);
    color: var(--text-primary, #c9d1d9);
    font-size: 18px;
    cursor: pointer;
    transition: background 0.2s;
  }

  .marp-nav button:hover {
    background: var(--bg-hover, #1c2128);
  }

  .marp-nav button:focus-visible {
    outline: 4px solid var(--focus-ring, #58a6ff);
    outline-offset: 2px;
  }

  .marp-nav button:disabled {
    opacity: 0.4;
    cursor: not-allowed;
  }

  .marp-progress {
    font-family: var(--font-mono, monospace);
    font-size: 14px;
    color: var(--text-secondary, #8b949e);
    min-width: 80px;
    text-align: center;
  }

  .marp-progress .current {
    color: var(--bs-blue, #58a6ff);
    font-weight: 600;
  }

  /* ─── Exit button ─────────────────────────────────────────────── */

  .marp-exit {
    position: absolute;
    top: 16px;
    right: 16px;
    z-index: 10;
    min-width: var(--touch-min, 48px);
    min-height: var(--touch-min, 48px);
    padding: 8px 16px;
    border: 1px solid var(--border-default, #30363d);
    border-radius: 6px;
    background: var(--bg-surface, #161b22);
    color: var(--text-primary, #c9d1d9);
    font-size: 16px;
    cursor: pointer;
    opacity: 0.8;
    transition: opacity 0.2s;
  }

  .marp-exit:hover {
    opacity: 1;
  }

  /* ─── TV overrides ────────────────────────────────────────────── */

  @media (min-width: 1800px) and (min-height: 800px) {
    .marp-slide-viewport section {
      padding: 72px;
      font-size: 36px;
    }
    .marp-slide-viewport h1 { font-size: 80px; }
    .marp-slide-viewport h2 { font-size: 64px; }
    .marp-slide-viewport p,
    .marp-slide-viewport li { font-size: 36px; }
    .marp-nav button {
      min-width: 72px;
      min-height: 72px;
      font-size: 24px;
    }
  }

  /* ─── Mobile overrides ────────────────────────────────────────── */

  @media (max-width: 720px) {
    .marp-slide-viewport section {
      padding: 24px;
    }
    .marp-slide-viewport h1 { font-size: 40px; }
    .marp-slide-viewport h2 { font-size: 32px; }
    .marp-slide-viewport p,
    .marp-slide-viewport li { font-size: 20px; }
    .marp-slide-viewport pre,
    .marp-slide-viewport code { font-size: 14px; }
    .marp-nav {
      flex-wrap: wrap;
      gap: 8px;
    }
    .marp-nav button {
      min-width: 44px;
      min-height: 44px;
      padding: 6px 16px;
      font-size: 14px;
    }
  }

  /* ─── Reduced motion ──────────────────────────────────────────── */

  @media (prefers-reduced-motion: reduce) {
    .marp-nav button {
      transition: none;
    }
  }
`;

// ─── MarpSlide Component ──────────────────────────────────────────

interface MarpSlideProps {
  content: string;
  theme?: string;
  className?: string;
}

export function MarpSlide({ content, theme = 'default', className = '' }: MarpSlideProps) {
  const [currentSlide, setCurrentSlide] = useState(0);
  const [totalSlides, setTotalSlides] = useState(0);
  const [slides, setSlides] = useState<string[]>([]);
  const [marpCSS, setMarpCSS] = useState('');
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    try {
      const marp = new Marp({
        inlineSVG: true,
        html: true,
      });

      const result = marp.render(content);

      // Split into individual slides
      const slideRegex = /<section[^>]*>([\s\S]*?)<\/section>/g;
      const slideMatches: string[] = [];
      let match;
      while ((match = slideRegex.exec(result.html)) !== null) {
        slideMatches.push(match[0]);
      }

      setSlides(slideMatches);
      setTotalSlides(slideMatches.length);
      setMarpCSS(result.css);
      setCurrentSlide(0);
    } catch (err) {
      console.error('Marp render error:', err);
      setSlides([]);
      setTotalSlides(0);
    }
  }, [content]);

  const goToSlide = useCallback((index: number) => {
    setCurrentSlide(Math.max(0, Math.min(index, totalSlides - 1)));
  }, [totalSlides]);

  const goNext = useCallback(() => {
    goToSlide(currentSlide + 1);
  }, [currentSlide, goToSlide]);

  const goPrev = useCallback(() => {
    goToSlide(currentSlide - 1);
  }, [currentSlide, goToSlide]);

  // Keyboard navigation
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'ArrowRight' || e.key === 'ArrowDown') {
        e.preventDefault();
        goNext();
      } else if (e.key === 'ArrowLeft' || e.key === 'ArrowUp') {
        e.preventDefault();
        goPrev();
      } else if (e.key === 'Home') {
        e.preventDefault();
        goToSlide(0);
      } else if (e.key === 'End') {
        e.preventDefault();
        goToSlide(totalSlides - 1);
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [goNext, goPrev, goToSlide, totalSlides]);

  if (totalSlides === 0) {
    // No slides detected — render as regular markdown
    return (
      <div className={`marp-slide-container ${className}`}>
        <style>{MARP_SLIDE_STYLES}</style>
        <div className="marp-slide-viewport">
          <div dangerouslySetInnerHTML={{ __html: content }} />
        </div>
      </div>
    );
  }

  return (
    <div className={`marp-slide-container ${className}`} ref={containerRef}>
      <style>{MARP_SLIDE_STYLES}</style>
      <style>{marpCSS}</style>

      {/* Current slide */}
      <div className="marp-slide-viewport">
        <div dangerouslySetInnerHTML={{ __html: slides[currentSlide] }} />
      </div>

      {/* Navigation */}
      <div className="marp-nav">
        <button
          onClick={goPrev}
          disabled={currentSlide === 0}
          aria-label="Previous slide"
        >
          ◀ Prev
        </button>

        <div className="marp-progress">
          <span className="current">{currentSlide + 1}</span>
          {' '}/ {totalSlides}
        </div>

        <button
          onClick={goNext}
          disabled={currentSlide === totalSlides - 1}
          aria-label="Next slide"
        >
          Next ▶
        </button>
      </div>
    </div>
  );
}

export default MarpSlide;
