import React, { useState, useEffect } from 'react'
import { GlobalToolbar, ToolbarTab } from '../../components/GlobalToolbar'
import { Icon } from '../../components/Icon'
import { useSurfaceShell } from '../../components/SurfaceShellContext'
import VaultSidebar from '../../components/VaultSidebar'
import AssistUISurface from '../assistui/AssistUISurface'
import '../../styles/userver.css'

// other module — extracted from UServerSurface.tsx
// Auto-generated by file-splitter on 20260618_220141




async function apiFetch<T>(path: string, options?: RequestInit): Promise<T | null> {
  try {
    const res = await fetch(`${API_BASE}${path}`, {
      headers: { 'Content-Type': 'application/json' },
      ...options,
    })
    if (!res.ok) return null
    return await res.json() as T
  } catch {
    return null
  }
}

// ─── Dashboard Tab ──────────────────────────────────────────────────

function DashboardTab({ services, workflows, logs, surfaces }: {
  services: ServiceStatus[]
  workflows: Workflow[]
  logs: LogEntry[]
  surfaces: SurfaceInfo[]
}) {
  const upCount = services.filter(s => s.status === 'up').length
  const degradedCount = services.filter(s => s.status === 'degraded').length
  const downCount = services.filter(s => s.status === 'down').length
  const runningWorkflows = workflows.filter(w => w.status === 'running').length

  return (
    <div className="userver-grid">
      {/* Welcome Card */}
      <div className="userver-card userver-welcome-card">
        <div className="userver-card-content">
          <h2 className="userver-heading">Server Operations</h2>
          <p className="userver-text">
            Monitoring {services.length} services · {workflows.length} workflows · {logs.length} log entries
          </p>
          <div className="userver-stats-row">
            <div className="userver-stat">
              <span className="userver-stat-value">{upCount}</span>
              <span className="userver-stat-label">Up</span>
            </div>
            <div className="userver-stat">
              <span className="userver-stat-value">{degradedCount}</span>
              <span className="userver-stat-label">Degraded</span>
            </div>
            <div className="userver-stat">
              <span className="userver-stat-value">{downCount}</span>
              <span className="userver-stat-label">Down</span>
            </div>
            <div className="userver-stat">
              <span className="userver-stat-value">{runningWorkflows}</span>
              <span className="userver-stat-label">Running</span>
            </div>
          </div>
        </div>
      </div>

      {/* Surfaces */}
      <div className="userver-card">
        <div className="userver-card-header">
          <h3>Surfaces</h3>
          <span className="userver-card-subtitle">uDos Connect surface registry</span>
        </div>
        <div className="userver-card-content">
          {surfaces.map(surface => (
            <div key={surface.name} className="userver-service-row">
              <div className="userver-service-info">
                <span className="userver-service-name">
                  <Icon name={surface.icon} size={16} style={{ marginRight: 6, color: surface.color }} />
                  {surface.label}
                </span>
                <span className="userver-service-desc">{surface.description}</span>
              </div>
              <div className="userver-service-meta">
                <a href={surface.url} className="userver-surface-link" style={{ color: surface.color }}>
                  :{surface.port}
                </a>
                <span className={`userver-service-status ${surface.status}`}>
                  {surface.status === 'running' ? 'Online' : 'Offline'}
                </span>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Service Status Summary */}
      <div className="userver-card">
        <div className="userver-card-header">
          <h3>Service Status</h3>
        </div>
        <div className="userver-card-content">
          {services.slice(0, 4).map(svc => (
            <div key={svc.name} className="userver-service-row">
              <div className="userver-service-info">
                <span className="userver-service-name">{svc.name}</span>
                <span className="userver-service-desc">{svc.description}</span>
              </div>
              <div className="userver-service-meta">
                <span className={`userver-service-status ${svc.status}`}>
                  {svc.status === 'up' ? 'Online' : svc.status === 'degraded' ? 'Degraded' : 'Offline'}
                </span>
                {svc.port > 0 && <span className="userver-service-port">:{svc.port}</span>}
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Recent Logs */}
      <div className="userver-card">
        <div className="userver-card-header">
          <h3>Recent Logs</h3>
        </div>
        <div className="userver-card-content">
          {logs.slice(0, 5).map((log, idx) => (
            <div key={idx} className="userver-log-entry">
              <span className="userver-log-time">{log.timestamp.slice(11, 19)}</span>
              <span className="userver-log-service">{log.service}</span>
              <span className={`userver-log-level ${log.level}`}>{log.level}</span>
              <span className="userver-log-message">{log.message}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Workflow Status */}
      <div className="userver-card">
        <div className="userver-card-header">
          <h3>Workflows</h3>
        </div>
        <div className="userver-card-content">
          {workflows.slice(0, 3).map(wf => (
            <div key={wf.name} className="userver-workflow-row">
              <div className="userver-workflow-info">
                <span className="userver-workflow-name">{wf.name}</span>
                <span className="userver-workflow-schedule">{wf.schedule}</span>
              </div>
              <div className="userver-workflow-meta">
                <span className={`userver-workflow-status ${wf.status}`}>
                  {wf.status.charAt(0).toUpperCase() + wf.status.slice(1)}
                </span>
                <span className="userver-workflow-lastrun">{wf.lastRun}</span>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}

// ─── Services Tab ───────────────────────────────────────────────────

function ServicesTab({ services }: { services: ServiceStatus[] }) {
  return (
    <div>
      <div className="userver-toolbar">
        <div className="userver-toolbar-left">
          <h2 className="userver-heading">Services</h2>
        </div>
      </div>
      <div className="userver-grid">
        {services.map(svc => (
          <div key={svc.name} className="userver-card">
            <div className="userver-card-header">
              <h3>{svc.name}</h3>
              <span className={`userver-service-status ${svc.status}`}>
                {svc.status === 'up' ? 'Online' : svc.status === 'degraded' ? 'Degraded' : 'Offline'}
              </span>
            </div>
            <div className="userver-card-content">
              <p className="userver-text" style={{ marginBottom: 8 }}>{svc.description}</p>
              <div className="userver-service-details">
                {svc.port > 0 && <span>Port: <strong>{svc.port}</strong></span>}
                <span>Type: <strong>{svc.type}</strong></span>
                <span>Uptime: <strong>{svc.uptime}%</strong></span>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}

// ─── Logs Tab ───────────────────────────────────────────────────────

function LogsTab({ logs }: { logs: LogEntry[] }) {
  const [filter, setFilter] = useState('')

  const filtered = filter
    ? logs.filter(log =>
        log.service.toLowerCase().includes(filter.toLowerCase()) ||
        log.message.toLowerCase().includes(filter.toLowerCase()) ||
        log.level.includes(filter.toLowerCase())
      )
    : logs

  return (
    <div>
      <div className="userver-toolbar">
        <div className="userver-toolbar-left">
          <h2 className="userver-heading">Logs</h2>
        </div>
      </div>
      <div className="userver-log-filter">
        <input
          type="text"
          placeholder="Filter by service, level, or message..."
          value={filter}
          onChange={e => setFilter(e.target.value)}
        />
        {filter && (
          <button className="userver-action-btn" onClick={() => setFilter('')}>Clear</button>
        )}
      </div>
      <div className="userver-card">
        <div className="userver-card-header">
          <h3>Log Entries ({filtered.length})</h3>
        </div>
        <div className="userver-card-content">
          {filtered.length === 0 ? (
            <p className="userver-text" style={{ textAlign: 'center', padding: 20 }}>
              No log entries match your filter.
            </p>
          ) : (
            filtered.map((log, idx) => (
              <div key={idx} className="userver-log-entry">
                <span className="userver-log-time">{log.timestamp}</span>
                <span className="userver-log-service">{log.service}</span>
                <span className={`userver-log-level ${log.level}`}>{log.level}</span>
                <span className="userver-log-message">{log.message}</span>
              </div>
            ))
          )}
        </div>
      </div>
    </div>
  )
}

// ─── Workflows Tab ──────────────────────────────────────────────────

function WorkflowsTab({ workflows }: { workflows: Workflow[] }) {
  return (
    <div>
      <div className="userver-toolbar">
        <div className="userver-toolbar-left">
          <h2 className="userver-heading">Workflows</h2>
        </div>
      </div>
      <div className="userver-grid">
        {workflows.map(wf => (
          <div key={wf.name} className="userver-card">
            <div className="userver-card-header">
              <h3>{wf.name}</h3>
              <span className={`userver-workflow-status ${wf.status}`}>
                {wf.status.charAt(0).toUpperCase() + wf.status.slice(1)}
              </span>
            </div>
            <div className="userver-card-content">
              <div className="userver-service-details">
                <span>Schedule: <strong>{wf.schedule}</strong></span>
                <span>Last run: <strong>{wf.lastRun}</strong></span>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}

// ─── Agent Router API ───────────────────────────────────────────────
const AGENT_ROUTER_URL = 'http://localhost:8486'

interface RouterAgent {
  id: string
  name: string
  capabilities: string[]
  status: string
  load: string
  costPerTask: number
  avgLatencyMs: number
  successRate: number
}

interface RouterStats {
  totalRouted: number
  totalErrors: number
  byAgent: Record<string, number>
  byCapability: Record<string, number>
  recentRoutes: Array<{ task: string; agent: string; capability: string; timestamp: string }>
}

// ─── Agents Tab ─────────────────────────────────────────────────────

function AgentsTab() {
  const [routerAgents, setRouterAgents] = useState<RouterAgent[]>([])
  const [routerStats, setRouterStats] = useState<RouterStats | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    let cancelled = false
    async function fetchData() {
      try {
        const [agentsRes, statsRes] = await Promise.all([
          fetch(`${AGENT_ROUTER_URL}/agents`, { signal: AbortSignal.timeout(3000) }),
          fetch(`${AGENT_ROUTER_URL}/stats`, { signal: AbortSignal.timeout(3000) }),
        ])
        if (agentsRes.ok) {
          const data = await agentsRes.json()
          if (!cancelled) setRouterAgents(data.agents || [])
        }
        if (statsRes.ok) {
          const data = await statsRes.json()
          if (!cancelled) setRouterStats(data)
        }
      } catch (e: any) {
        if (!cancelled) setError(e.message || 'Agent Router unreachable')
      }
      if (!cancelled) setLoading(false)
    }
    fetchData()
    const interval = setInterval(fetchData, 10000)
    return () => { cancelled = true; clearInterval(interval) }
  }, [])

  if (loading) {
    return (
      <div className="userver-toolbar">
        <div className="userver-toolbar-left">
          <h2 className="userver-heading">Agents</h2>
          <span className="userver-card-subtitle">Loading from Agent Router...</span>
        </div>
      </div>
    )
  }

  if (error || routerAgents.length === 0) {
    return (
      <div>
        <div className="userver-toolbar">
          <div className="userver-toolbar-left">
            <h2 className="userver-heading">Agents</h2>
          </div>
        </div>
        <div className="userver-card" style={{ margin: 16, padding: 24, textAlign: 'center' }}>
          <p className="userver-text" style={{ color: 'var(--pico-del-color, #f85149)' }}>
            ⚠️ Agent Router unavailable — start agent-router on port 8486
          </p>
          <p className="userver-text" style={{ marginTop: 8, fontSize: 12 }}>
            {error || 'No agents registered'}
          </p>
        </div>
      </div>
    )
  }

  const onlineCount = routerAgents.filter(a => a.status === 'online').length
  const totalRouted = routerStats?.totalRouted || 0
  const totalErrors = routerStats?.totalErrors || 0

  return (
    <div>
      <div className="userver-toolbar">
        <div className="userver-toolbar-left">
          <h2 className="userver-heading">Agents</h2>
          <span className="userver-card-subtitle">
            {onlineCount}/{routerAgents.length} online · {totalRouted} routed · {totalErrors} errors
          </span>
        </div>
      </div>
      <div className="userver-grid">
        {routerAgents.map(agent => {
          const loadMatch = agent.load.match(/(\d+)\/(\d+)/)
          const currentLoad = loadMatch ? parseInt(loadMatch[1]) : 0
          const maxLoad = loadMatch ? parseInt(loadMatch[2]) : 1
          const loadPct = Math.round((currentLoad / maxLoad) * 100)
          const isOnline = agent.status === 'online'
          const agentTasks = routerStats?.byAgent?.[agent.id] || 0

          return (
            <div key={agent.id} className="userver-card" style={{ borderLeft: `3px solid ${isOnline ? 'var(--pico-ins-color, #3fb950)' : 'var(--pico-del-color, #f85149)'}` }}>
              <div className="userver-card-header">
                <h3>{agent.name}</h3>
                <span className={`userver-service-status ${isOnline ? 'up' : 'down'}`}>
                  {isOnline ? 'Online' : 'Offline'}
                </span>
              </div>
              <div className="userver-card-content">
                <div className="userver-service-details" style={{ flexWrap: 'wrap', gap: 8, marginBottom: 8 }}>
                  <span>Cost: <strong>${agent.costPerTask.toFixed(4)}</strong></span>
                  <span>Latency: <strong>{agent.avgLatencyMs}ms</strong></span>
                  <span>Success: <strong>{(agent.successRate * 100).toFixed(0)}%</strong></span>
                  <span>Tasks: <strong>{agentTasks}</strong></span>
                </div>
                {/* Load bar */}
                <div style={{ marginBottom: 8 }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 11, color: 'var(--pico-muted-color, #8b949e)', marginBottom: 2 }}>
                    <span>Load</span>
                    <span>{agent.load}</span>
                  </div>
                  <div style={{ height: 4, background: 'var(--pico-border-color, #30363d)', borderRadius: 2, overflow: 'hidden' }}>
                    <div style={{ width: `${loadPct}%`, height: '100%', background: isOnline ? 'var(--pico-ins-color, #3fb950)' : 'var(--pico-del-color, #f85149)', borderRadius: 2, transition: 'width 0.5s' }} />
                  </div>
                </div>
                {/* Capabilities */}
                <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4 }}>
                  {agent.capabilities.map(cap => (
                    <span key={cap} style={{
                      fontSize: 10, padding: '1px 5px', borderRadius: 3,
                      background: 'var(--pico-card-sectioning-background-color, #1c2128)',
                      color: 'var(--pico-primary, #58a6ff)',
                      fontFamily: 'monospace',
                    }}>
                      {cap}
                    </span>
                  ))}
                </div>
              </div>
            </div>
          )
        })}
      </div>

      {/* Recent Routes */}
      {routerStats?.recentRoutes && routerStats.recentRoutes.length > 0 && (
        <div className="userver-card" style={{ margin: '0 16px 16px' }}>
          <div className="userver-card-header">
            <h3>Recent Routes</h3>
          </div>
          <div className="userver-card-content">
            {routerStats.recentRoutes.slice(-5).reverse().map((route, i) => (
              <div key={i} className="userver-log-entry">
                <span className="userver-log-time">{route.timestamp?.slice(11, 19) || '--:--:--'}</span>
                <span className="userver-log-service">{route.agent}</span>
                <span style={{ fontSize: 10, padding: '1px 4px', borderRadius: 3, background: 'var(--pico-card-sectioning-background-color, #1c2128)', color: 'var(--pico-primary, #58a6ff)', fontFamily: 'monospace' }}>
                  {route.capability}
                </span>
                <span className="userver-log-message">{route.task}</span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  )
}

// ─── Publishing Tab ─────────────────────────────────────────────────
interface PublishedDoc {
  slug: string
  title: string
  status: 'synced' | 'stale' | 'missing'
  lastSync: string
}

const DEFAULT_PUBLISHED_DOCS: PublishedDoc[] = [
  { slug: 'architecture-overview', title: 'Architecture Overview', status: 'synced', lastSync: '2026-06-18' },
  { slug: 'devstudio-guide', title: 'DevStudio Guide', status: 'synced', lastSync: '2026-06-18' },
  { slug: 'dev-workflow', title: 'Dev Workflow', status: 'synced', lastSync: '2026-06-18' },
  { slug: 'configuration', title: 'Configuration', status: 'synced', lastSync: '2026-06-18' },
  { slug: 'user-guide', title: 'User Guide', status: 'synced', lastSync: '2026-06-18' },
  { slug: 'cli-tools', title: 'CLI Tools', status: 'synced', lastSync: '2026-06-18' },
  { slug: 'skills-pipeline', title: 'Skills Pipeline', status: 'synced', lastSync: '2026-06-18' },
  { slug: 'narrator-system', title: 'Narrator System', status: 'synced', lastSync: '2026-06-18' },
  { slug: 'snackbar-api', title: 'Snackbar API', status: 'synced', lastSync: '2026-06-18' },
  { slug: 'changelog', title: 'Changelog', status: 'synced', lastSync: '2026-06-18' },
  { slug: 'roadmap-overview', title: 'Roadmap Overview', status: 'synced', lastSync: '2026-06-18' },
  { slug: 'surfaces-guide', title: 'Surfaces Guide', status: 'synced', lastSync: '2026-06-18' },
  { slug: 'scripts', title: 'Scripts', status: 'synced', lastSync: '2026-06-18' },
  { slug: 'extensions', title: 'Extensions', status: 'synced', lastSync: '2026-06-18' },
  { slug: 'modules', title: 'Modules', status: 'synced', lastSync: '2026-06-18' },
]

const PUBLISHING_WORKFLOWS = [
  { name: 'daily-docs-sync', status: 'completed', lastRun: '2026-06-18 04:00', schedule: '0 4 * * *', service: 'docs-site-sync' },
  { name: 'docs-publisher', status: 'idle', lastRun: '2026-06-17 12:00', schedule: '0 12 * * *', service: 'docs-publisher' },
]



function PublishingTab() {
  const [syncing, setSyncing] = useState(false)
  const [buildStatus, setBuildStatus] = useState<string | null>(null)
  const [docs] = useState<PublishedDoc[]>(DEFAULT_PUBLISHED_DOCS)

  const syncedCount = docs.filter(d => d.status === 'synced').length
  const staleCount = docs.filter(d => d.status === 'stale').length

  const handleSync = async () => {
    setSyncing(true)
    setBuildStatus(null)
    try {
      const res = await fetch('http://localhost:8484/api/docs/sync', { method: 'POST', signal: AbortSignal.timeout(30000) })
      if (res.ok) {
        setBuildStatus('success')
      } else {
        setBuildStatus('error')
      }
    } catch {
      setBuildStatus('error')
    }
    setSyncing(false)
  }

  return (
    <div>
      <div className="userver-toolbar">
        <div className="userver-toolbar-left">
          <h2 className="userver-heading">Publishing</h2>
          <span className="userver-card-subtitle">
            {syncedCount} synced · {staleCount} stale
          </span>
        </div>
        <div className="userver-toolbar-right">
          <button
            className="userver-action-btn"
            onClick={handleSync}
            disabled={syncing}
          >
            {syncing ? 'Syncing...' : 'Sync Now'}
          </button>
        </div>
      </div>

      {/* Build Status */}
      {buildStatus && (
        <div className={`userver-card`} style={{ margin: '0 16px 16px', borderLeft: `3px solid ${buildStatus === 'success' ? 'var(--pico-ins-color, #3fb950)' : 'var(--pico-del-color, #f85149)'}` }}>
          <div className="userver-card-content">
            <p className="userver-text">
              {buildStatus === 'success' ? '✅ Docs synced and Jekyll site rebuilt successfully' : '❌ Sync failed — check the docs-site-sync service logs'}
            </p>
          </div>
        </div>
      )}

      {/* Publishing Workflows */}
      <div className="userver-card" style={{ margin: '0 16px 16px' }}>
        <div className="userver-card-header">
          <h3>Publishing Workflows</h3>
        </div>
        <div className="userver-card-content">
          {PUBLISHING_WORKFLOWS.map(wf => (
            <div key={wf.name} className="userver-workflow-row">
              <div className="userver-workflow-info">
                <span className="userver-workflow-name">{wf.name}</span>
                <span className="userver-workflow-schedule">{wf.service} · {wf.schedule}</span>
              </div>
              <div className="userver-workflow-meta">
                <span className={`userver-workflow-status ${wf.status}`}>
                  {wf.status.charAt(0).toUpperCase() + wf.status.slice(1)}
                </span>
                <span className="userver-workflow-lastrun">{wf.lastRun}</span>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Published Docs */}
      <div className="userver-card" style={{ margin: '0 16px 16px' }}>
        <div className="userver-card-header">
          <h3>Published Guides</h3>
          <span className="userver-card-subtitle">
            <a href="http://localhost:4000/DevStudio/" target="_blank" rel="noopener noreferrer" style={{ color: 'var(--pico-primary, #58a6ff)' }}>
              View site ↗
            </a>
          </span>
        </div>
        <div className="userver-card-content">
          <div className="userver-grid" style={{ gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))' }}>
            {docs.map(doc => (
              <div key={doc.slug} className="userver-service-row" style={{ padding: '8px 0', borderBottom: '1px solid var(--pico-border-color, #30363d)' }}>
                <div className="userver-service-info">
                  <span className="userver-service-name">{doc.title}</span>
                  <span className="userver-service-desc">/{doc.slug}</span>
                </div>
                <div className="userver-service-meta">
                  <span className={`userver-service-status ${doc.status === 'synced' ? 'up' : 'degraded'}`}>
                    {doc.status === 'synced' ? 'Synced' : doc.status === 'stale' ? 'Stale' : 'Missing'}
                  </span>
                  <span className="userver-service-port" style={{ fontSize: 11 }}>{doc.lastSync}</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Publishing Flow Info */}
      <div className="userver-card" style={{ margin: '0 16px 16px' }}>
        <div className="userver-card-header">
          <h3>Publishing Pipeline</h3>
        </div>
        <div className="userver-card-content">
          <div style={{ display: 'flex', flexDirection: 'column', gap: 8, fontSize: 13 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <span style={{ color: 'var(--pico-muted-color, #8b949e)' }}>①</span>
              <span><strong>DevStudio docs/</strong> — source of truth (raw markdown)</span>
            </div>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <span style={{ color: 'var(--pico-muted-color, #8b949e)' }}>②</span>
              <span><strong>docs-site-sync</strong> — syncs docs → Jekyll guide/ directory</span>
            </div>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <span style={{ color: 'var(--pico-muted-color, #8b949e)' }}>③</span>
              <span><strong>Jekyll build</strong> — generates static HTML site</span>
            </div>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <span style={{ color: 'var(--pico-muted-color, #8b949e)' }}>④</span>
              <span><strong>GitHub Pages</strong> — publishes gh-pages branch</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

// ─── Main Surface ───────────────────────────────────────────────────
export function UServerSurface() {
  const [tab, setTab] = useState<UServerTab>('dashboard')
  const [services] = useState<ServiceStatus[]>(DEFAULT_SERVICES)
  const [logs] = useState<LogEntry[]>(DEFAULT_LOGS)
  const [workflows] = useState<Workflow[]>(DEFAULT_WORKFLOWS)
  const [agents] = useState<AgentInfo[]>(DEFAULT_AGENTS)
  const [surfaces] = useState<SurfaceInfo[]>(DEFAULT_SURFACES)
  const [chatOpen, setChatOpen] = useState(false)
  const { sidebarOpen, toggleSidebar } = useSurfaceShell()
  const runningCount = surfaces.filter(s => s.status === 'running').length

  const tabs: ToolbarTab[] = [
    { id: 'dashboard', icon: 'home', label: 'Dashboard', active: tab === 'dashboard', onClick: () => setTab('dashboard') },
    { id: 'services', icon: 'settings', label: 'Services', active: tab === 'services', onClick: () => setTab('services') },
    { id: 'logs', icon: 'article', label: 'Logs', active: tab === 'logs', onClick: () => setTab('logs') },
    { id: 'workflows', icon: 'layers', label: 'Workflows', active: tab === 'workflows', onClick: () => setTab('workflows') },
    { id: 'agents', icon: 'smart_toy', label: 'Agents', active: tab === 'agents', onClick: () => setTab('agents') },
    { id: 'publishing', icon: 'menu_book', label: 'Publishing', active: tab === 'publishing', onClick: () => setTab('publishing') },
  ]

  return (
    <div className="userver-surface">
      <GlobalToolbar
        tabs={tabs}
        chatMode={chatOpen ? 'panel' : 'closed'}
        onToggleChat={() => setChatOpen(prev => !prev)}
        onToggleSidebar={toggleSidebar}
        sidebarOpen={sidebarOpen}
        rightExtra={
          <span className="hub-status-badge">
            <span className={`hub-status-dot ${runningCount > 0 ? 'hub-status-dot--online' : ''}`} />
            {runningCount}/{surfaces.length} online
          </span>
        }
      />

      <div className="usx-surface-body" style={{ position: 'relative' }}>
        <VaultSidebar open={sidebarOpen} onToggle={toggleSidebar} />

        {/* ─── Chat Panel — overlays ALL surfaces (absolute, z-index) ─── */}
        {chatOpen && (
          <div className="hub-chat-panel" style={{ position: 'absolute', top: 0, right: 0, bottom: 0, width: 380, zIndex: 1000, display: 'flex', flexDirection: 'column' }}>
            <div className="hub-chat-panel-header">
              <span className="hub-chat-panel-title">Chat</span>
              <button className="usx-header-btn" onClick={() => setChatOpen(false)} title="Close chat">
                <Icon name="close" size={16} />
              </button>
            </div>
            <div className="hub-chat-panel-body" style={{ flex: 1, overflow: 'hidden' }}>
              <AssistUISurface hideToolbar />
            </div>
          </div>
        )}

        <main className="usx-surface-main">
          {tab === 'dashboard' && <DashboardTab services={services} workflows={workflows} logs={logs} surfaces={surfaces} />}
          {tab === 'services' && <ServicesTab services={services} />}
          {tab === 'logs' && <LogsTab logs={logs} />}
          {tab === 'workflows' && <WorkflowsTab workflows={workflows} />}
          {tab === 'agents' && <AgentsTab />}
          {tab === 'publishing' && <PublishingTab />}
        </main>
      </div>
    </div>
  )
}

