import React, { useState, useEffect } from 'react'
import { GlobalToolbar, ToolbarTab } from '../../components/GlobalToolbar'
import { Icon } from '../../components/Icon'
import { useSurfaceShell } from '../../components/SurfaceShellContext'
import VaultSidebar from '../../components/VaultSidebar'
import AssistUISurface from '../assistui/AssistUISurface'
import '../../styles/userver.css'

// surfaces module — extracted from UServerSurface.tsx
// Auto-generated by file-splitter on 20260618_220141



export default function UServerSurface() {
  const [tab, setTab] = useState<UServerTab>('dashboard')
  const [services] = useState<ServiceStatus[]>(DEFAULT_SERVICES)
  const [logs] = useState<LogEntry[]>(DEFAULT_LOGS)
  const [workflows] = useState<Workflow[]>(DEFAULT_WORKFLOWS)
  const [agents] = useState<AgentInfo[]>(DEFAULT_AGENTS)
  const [surfaces] = useState<SurfaceInfo[]>(DEFAULT_SURFACES)
  const [chatOpen, setChatOpen] = useState(false)
  const { sidebarOpen, toggleSidebar } = useSurfaceShell()
  const runningCount = surfaces.filter(s => s.status === 'running').length

  const tabs: ToolbarTab[] = [
    { id: 'dashboard', icon: 'home', label: 'Dashboard', active: tab === 'dashboard', onClick: () => setTab('dashboard') },
    { id: 'services', icon: 'settings', label: 'Services', active: tab === 'services', onClick: () => setTab('services') },
    { id: 'logs', icon: 'article', label: 'Logs', active: tab === 'logs', onClick: () => setTab('logs') },
    { id: 'workflows', icon: 'layers', label: 'Workflows', active: tab === 'workflows', onClick: () => setTab('workflows') },
    { id: 'agents', icon: 'smart_toy', label: 'Agents', active: tab === 'agents', onClick: () => setTab('agents') },
    { id: 'publishing', icon: 'menu_book', label: 'Publishing', active: tab === 'publishing', onClick: () => setTab('publishing') },
  ]

  return (
    <div className="userver-surface">
      <GlobalToolbar
        tabs={tabs}
        chatMode={chatOpen ? 'panel' : 'closed'}
        onToggleChat={() => setChatOpen(prev => !prev)}
        onToggleSidebar={toggleSidebar}
        sidebarOpen={sidebarOpen}
        rightExtra={
          <span className="hub-status-badge">
            <span className={`hub-status-dot ${runningCount > 0 ? 'hub-status-dot--online' : ''}`} />
            {runningCount}/{surfaces.length} online
          </span>
        }
      />

      <div className="usx-surface-body" style={{ position: 'relative' }}>
        <VaultSidebar open={sidebarOpen} onToggle={toggleSidebar} />

        {/* ─── Chat Panel — overlays ALL surfaces (absolute, z-index) ─── */}
        {chatOpen && (
          <div className="hub-chat-panel" style={{ position: 'absolute', top: 0, right: 0, bottom: 0, width: 380, zIndex: 1000, display: 'flex', flexDirection: 'column' }}>
            <div className="hub-chat-panel-header">
              <span className="hub-chat-panel-title">Chat</span>
              <button className="usx-header-btn" onClick={() => setChatOpen(false)} title="Close chat">
                <Icon name="close" size={16} />
              </button>
            </div>
            <div className="hub-chat-panel-body" style={{ flex: 1, overflow: 'hidden' }}>
              <AssistUISurface hideToolbar />
            </div>
          </div>
        )}

        <main className="usx-surface-main">
          {tab === 'dashboard' && <DashboardTab services={services} workflows={workflows} logs={logs} surfaces={surfaces} />}
          {tab === 'services' && <ServicesTab services={services} />}
          {tab === 'logs' && <LogsTab logs={logs} />}
          {tab === 'workflows' && <WorkflowsTab workflows={workflows} />}
          {tab === 'agents' && <AgentsTab />}
          {tab === 'publishing' && <PublishingTab />}
        </main>
      </div>
    </div>
  )
}

