// USystemSurface — slim entry point (modules split by file-splitter)
// Auto-generated by file-splitter on 20260618_220144



export * from "./USystemSurface_other";  // other
export * from "./USystemSurface_pages";  // pages
export * from "./USystemSurface_surfaces";  // surfaces
export { default } from "./USystemSurface_surfaces";  // re-export default (USystemSurface)

// Original file backed up to:
//   /Users/fredbook/.snackbar/backups/file-splitter/20260618_220144_USystemSurface.tsx