import React, { useState, useEffect, useCallback } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import { Icon } from '../../components/Icon'
import { GlobalToolbar, ToolbarTab } from '../../components/GlobalToolbar'
import { useSurfaceShell } from '../../components/SurfaceShellContext'
import VaultSidebar from '../../components/VaultSidebar'
import StoryView from '../../components/StoryView'
import { FeedPanel } from '../gridui/panels/FeedPanel'
import { SettingsPanel } from './SettingsPanel'
import { GridUIContext } from '../gridui/GridUIStore'
import '../../styles/hub/index.css'
import '../../styles/global-toolbar.css'

// pages module — extracted from USystemSurface.tsx
// Auto-generated by file-splitter on 20260618_220144



function PagesPanel() {
  const [activeCategory, setActiveCategory] = useState<string>('All')
  const categories = ['All', ...new Set(S_PAGES.map(p => p.category))]

  const filtered = activeCategory === 'All'
    ? S_PAGES
    : S_PAGES.filter(p => p.category === activeCategory)

  return (
    <div className="hub-apps">
      <div className="hub-apps-section">
        <div className="hub-apps-section-header">
          <Icon name="menu_book" size={18} />
          <h3>System Pages</h3>
          <p>S100–S899 system page registry</p>
        </div>

        <div className="hub-apps-section-toggle">
          {categories.map(cat => (
            <button
              key={cat}
              className={`hub-btn ${activeCategory === cat ? 'hub-btn--primary' : 'hub-btn--info'}`}
              onClick={() => setActiveCategory(cat)}
            >
              {cat}
            </button>
          ))}
        </div>

        <div className="hub-apps-grid">
          {filtered.map(page => (
            <div key={page.code} className="hub-app-card" style={{ '--hub-app-color': page.color } as React.CSSProperties}>
              <div className="hub-app-card-header">
                <div className="hub-app-card-icon" style={{ background: `${page.color}20`, color: page.color }}>
                  <Icon name={page.icon} size={24} />
                </div>
                <div className="hub-app-card-info">
                  <h3 className="hub-app-card-title">{page.title}</h3>
                  <p className="hub-app-card-subtitle" style={{ color: page.color }}>{page.code.toUpperCase()}</p>
                </div>
              </div>
              <p className="hub-app-card-desc">{page.description}</p>
              <div className="hub-app-card-footer">
                <span className="hub-app-card-badge">{page.category}</span>
                <button className="hub-btn hub-btn--primary" onClick={() => window.location.href = `/${page.code}`}>
                  Open
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}

// ─── Fallback GridUIContext for FeedPanel when rendered outside GridUI ──
function FeedPanelWithContext() {
  const fallbackStore = React.useMemo(() => ({
    showSnackbar: (msg: any) => console.log('[FeedPanel]', msg),
    activePanel: 'feeds' as const,
    setActivePanel: () => {},
    activePanelMeta: null,
    isDark: true,
    toggleTheme: () => {},
    fontSize: 14,
    increaseFontSize: () => {},
    decreaseFontSize: () => {},
    setFontSize: () => {},
    fontStyle: 'sans' as const,
    setFontStyle: () => {},
    gridFont: 'petme128' as const,
    setGridFont: () => {},
    viewport: { cols: 48, rows: 36, zoom: 1, bgColor: '#0d1117', gridColor: '#21262d', textColor: '#e6edf3', surfaceBgColor: '#010409', borderMode: 1 as const, borderBgColor: '#0d1117' },
    setViewport: () => {},
    applyViewportPreset: () => {},
    viewportPopupOpen: false,
    toggleViewportPopup: () => {},
    terminalViewport: { cols: 64, rows: 36, zoom: 1, bgColor: '#0d1117', gridColor: '#21262d', textColor: '#e6edf3', surfaceBgColor: '#010409', borderMode: 1 as const, borderBgColor: '#0d1117' },
    teletextViewport: { cols: 48, rows: 36, zoom: 1, bgColor: '#0d1117', gridColor: '#21262d', textColor: '#e6edf3', surfaceBgColor: '#010409', borderMode: 1 as const, borderBgColor: '#0d1117' },
    gridLayers: [],
    toggleLayer: () => {},
    setLayerVisibility: () => {},
    setLayerOpacity: () => {},
    addLayer: () => {},
    removeLayer: () => {},
    displayMode: 'teletext' as const,
    setGridDisplayMode: () => {},
    gridCells: [],
    setGridCells: () => {},
    updateCell: () => {},
    navRailCollapsed: false,
    toggleNavRail: () => {},
    activeSnackbar: null,
    dismissSnackbar: () => {},
  }), [])
  return (
    <GridUIContext.Provider value={fallbackStore as any}>
      <FeedPanel />
    </GridUIContext.Provider>
  )
}

// ─── Main Component ────────────────────────────────────────────────
export function USystemSurface() {

  const location = useLocation()
  const navigate = useNavigate()
  const { sidebarOpen, toggleSidebar } = useSurfaceShell()

  // Derive active tab from URL query param on every location change.
  // This avoids flash: the tab is computed synchronously during render,
  // and updates immediately when the URL changes (e.g. gear icon → /system?tab=settings).
  const activeTab: SystemTab = (() => {
    const params = new URLSearchParams(location.search)
    const tabParam = params.get('tab')
    const validTabs: SystemTab[] = ['install', 'modules', 'feeds', 'story', 'pages', 'settings']
    if (tabParam && (validTabs as string[]).includes(tabParam)) {
      return tabParam as SystemTab
    }
    return 'install'
  })()

  const renderContent = () => {
    switch (activeTab) {
      case 'install':
        return <InstallPanel />
      case 'modules':
        return <ModulesPanel />
      case 'feeds':
        return <FeedPanelWithContext />
      case 'story':
        return <StoryView />
      case 'pages':
        return <PagesPanel />
      case 'settings':
        return <SettingsPanel />
      default:
        return <InstallPanel />
    }
  }

  return (
    <div className="usx-surface-layout">
      <GlobalToolbar
        tabs={SYSTEM_TABS.map(t => ({
          id: t.id,
          icon: t.icon,
          label: t.label,
          active: activeTab === t.id,
          onClick: () => navigate(`/system?tab=${t.id}`),
        }))}
        onToggleSidebar={toggleSidebar}
        sidebarOpen={sidebarOpen}
      />
      <div className="usx-surface-body">
        <VaultSidebar open={sidebarOpen} onToggle={toggleSidebar} />
        <main className="usx-surface-main">
          {renderContent()}
        </main>
      </div>
    </div>
  )
}

