// surfaces module — extracted from USystemSurface.tsx
// Auto-generated by file-splitter on 20260618_220144



export default function USystemSurface() {

  const location = useLocation()
  const navigate = useNavigate()
  const { sidebarOpen, toggleSidebar } = useSurfaceShell()

  // Derive active tab from URL query param on every location change.
  // This avoids flash: the tab is computed synchronously during render,
  // and updates immediately when the URL changes (e.g. gear icon → /system?tab=settings).
  const activeTab: SystemTab = (() => {
    const params = new URLSearchParams(location.search)
    const tabParam = params.get('tab')
    const validTabs: SystemTab[] = ['install', 'modules', 'feeds', 'story', 'pages', 'settings', 'secrets']
    if (tabParam && (validTabs as string[]).includes(tabParam)) {
      return tabParam as SystemTab
    }
    return 'install'
  })()

  const renderContent = () => {
    switch (activeTab) {
      case 'install':
        return <InstallPanel />
      case 'modules':
        return <ModulesPanel />
      case 'feeds':
        return <FeedPanelWithContext />
      case 'story':
        return <StoryView />
      case 'pages':
        return <PagesPanel />
      case 'settings':
        return <SettingsPanel />
      case 'secrets':
        return <SecretStorePanel />
      default:
        return <InstallPanel />
    }
  }

  return (
    <div className="usx-surface-layout">
      <GlobalToolbar
        tabs={SYSTEM_TABS.map(t => ({
          id: t.id,
          icon: t.icon,
          label: t.label,
          active: activeTab === t.id,
          onClick: () => navigate(`/system?tab=${t.id}`),
        }))}
        onToggleSidebar={toggleSidebar}
        sidebarOpen={sidebarOpen}
      />
      <div className="usx-surface-body">
        <VaultSidebar open={sidebarOpen} onToggle={toggleSidebar} />
        <main className="usx-surface-main">
          {renderContent()}
        </main>
      </div>
    </div>
  )
}

