from __future__ import annotations

"""health module — extracted from mcp_bridge.py"""
# Auto-generated by file-splitter on 20260618_215801

"""
MCP Bridge — Cross-Machine Tool & Skill Execution
==================================================
Proxies MCP tool calls and skill execution to remote peers (e.g., Forge).

Architecture:
    Wizard MCP Client
           │
           ▼
    Wizard Snackbar (/v1/mcp/bridge/call)
           │
           ├── Local MCP tools (direct)
           │
           └── Forge Snackmachine (file-based JSONL queue)
                     │
                     └── Forge local execution (spices/skills)

Transport backends:
  - HTTP:   POST /v1/mcp/call on remote Snackbar (for future HTTP peers)
  - File:   JSONL queue → Snackmachine commands.jsonl → replies.jsonl
  - SSH:    (future) direct SSH command execution

Usage:
    from mcp_bridge import MCPBridge
    bridge = MCPBridge()
    result = await bridge.call_tool("forge", "copernicus.search", {"query": "test"})
"""


import json
import time
import os
import uuid
import logging
from pathlib import Path
from typing import Optional
from urllib.parse import urljoin

try:
    from aiohttp import ClientSession, ClientTimeout
except ImportError:
    ClientSession = None
    ClientTimeout = None



    def check_health(self) -> bool:
        """Check if Snackmachine is reachable by verifying the replies path exists."""
        return self.replies_path.exists()

    def list_available(self) -> dict:
        """List available spices and skills by reading the Snackmachine spool."""
        spices = []
        skills = []

        if self.replies_path.exists():
            with open(self.replies_path) as f:
                for line in f:
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        entry = json.loads(line)
                        if entry.get("type") == "list_spices":
                            spices = entry.get("spices", [])
                        elif entry.get("type") == "list_skills":
                            skills = entry.get("skills", [])
                    except json.JSONDecodeError:
                        continue

        return {
            "spices": spices,
            "skills": skills,
        }


class MCPBridge:
    """Cross-machine MCP tool and skill execution bridge."""

    def __init__(self, peers: Optional[dict] = None):
        self.peers = peers or DEFAULT_PEERS.copy()
        self._session: Optional[ClientSession] = None
        self._timeout = ClientTimeout(total=30) if ClientTimeout else None
        self._snackmachine_transports: dict[str, SnackmachineTransport] = {}

    async def _get_session(self) -> ClientSession:
        if self._session is None or self._session.closed:
            if ClientSession is None:
                raise RuntimeError("aiohttp is required for MCP bridge")
            self._session = ClientSession()
        return self._session

    async def close(self):
        if self._session and not self._session.closed:
            await self._session.close()

    def _get_snackmachine_transport(self, peer_id: str) -> Optional[SnackmachineTransport]:
        """Get or create a SnackmachineTransport for a peer."""
        if peer_id not in self._snackmachine_transports:
            peer = self.peers.get(peer_id)
            if not peer or "snackmachine" not in peer:
                return None
            self._snackmachine_transports[peer_id] = SnackmachineTransport(peer["snackmachine"])
        return self._snackmachine_transports[peer_id]

    # ── Peer Management ─────────────────────────────────────────────

    def get_peers(self) -> dict:
        """Return all known peers with their status."""
        return self.peers

    def get_peer(self, peer_id: str) -> Optional[dict]:
        """Get a specific peer by ID."""
        return self.peers.get(peer_id)



    def set_peer_status(self, peer_id: str, status: str):
        """Update a peer's status (online/offline)."""
        if peer_id in self.peers:
            self.peers[peer_id]["status"] = status



    async def check_peer_health(self, peer_id: str) -> dict:
        """Check if a peer is reachable.

        Uses the appropriate transport:
          - HTTP:        GET /v1/health on the remote endpoint
          - snackmachine: Check if the replies file exists
        """
        peer = self.peers.get(peer_id)
        if not peer:
            return {"peer": peer_id, "status": "unknown", "error": "Unknown peer"}

        transport = peer.get("transport", "http")

        # ── Snackmachine file-based health check ──
        if transport == "snackmachine":
            sm = self._get_snackmachine_transport(peer_id)
            if sm and sm.check_health():
                self.peers[peer_id]["status"] = "online"
                return {
                    "peer": peer_id,
                    "status": "online",
                    "transport": "snackmachine",
                    "latency_ms": 0,
                }
            else:
                self.peers[peer_id]["status"] = "offline"
                return {
                    "peer": peer_id,
                    "status": "offline",
                    "transport": "snackmachine",
                    "error": "Snackmachine replies file not found",
                }

        # ── HTTP health check ──
        endpoint = peer["endpoint"]
        try:
            session = await self._get_session()
            start = time.time()
            async with session.get(
                urljoin(endpoint + "/", "v1/health"),
                timeout=self._timeout,
            ) as resp:
                latency_ms = int((time.time() - start) * 1000)
                if resp.status == 200:
                    data = await resp.json()
                    self.peers[peer_id]["status"] = "online"
                    return {
                        "peer": peer_id,
                        "status": "online",
                        "latency_ms": latency_ms,
                        "version": data.get("version", "unknown"),
                        "device": data.get("device", "unknown"),
                    }
                else:
                    self.peers[peer_id]["status"] = "offline"
                    return {
                        "peer": peer_id,
                        "status": "offline",
                        "error": f"HTTP {resp.status}",
                    }
        except Exception as e:
            self.peers[peer_id]["status"] = "offline"
            return {
                "peer": peer_id,
                "status": "offline",
                "error": str(e),
            }

    async def check_all_peers(self) -> list[dict]:
        """Check health of all known peers."""
        results = []
        for peer_id in self.peers:
            result = await self.check_peer_health(peer_id)
            results.append(result)
        return results

    # ── MCP Tool Bridge ─────────────────────────────────────────────

    async def call_tool(self, peer_id: str, tool: str, params: dict = None) -> dict:
        """Call an MCP tool on a remote peer.

        Uses the appropriate transport:
          - HTTP:        POST /v1/mcp/call on the remote endpoint
          - snackmachine: Write command to JSONL queue, poll for reply
        """
        peer = self.peers.get(peer_id)
        if not peer:
            return {"success": False, "error": f"Unknown peer: {peer_id}"}

        transport = peer.get("transport", "http")

        # ── Snackmachine file-based transport ──
        if transport == "snackmachine":
            return await self._call_tool_snackmachine(peer_id, tool, params)

        # ── HTTP transport ──
        return await self._call_tool_http(peer_id, tool, params)

    async def _call_tool_snackmachine(self, peer_id: str, tool: str, params: dict = None) -> dict:
        """Call a tool via Snackmachine file-based JSONL queue."""
        sm = self._get_snackmachine_transport(peer_id)
        if not sm:
            return {"success": False, "error": f"No Snackmachine transport for peer: {peer_id}"}

        # Check health first
        if not sm.check_health():
            self.peers[peer_id]["status"] = "offline"
            return {"success": False, "error": f"Peer {peer_id} is offline (replies file not found)"}

        self.peers[peer_id]["status"] = "online"
        start = time.time()

        # Write the command to the Snackmachine queue
        cmd = {
            "type": "run_spice" if tool.startswith("spice:") else "run_skill",
            "name": tool.replace("spice:", "").replace("skill:", ""),
            "params": params or {},
        }
        correlation_id = sm.write_command(cmd)

        # Poll for the reply
        reply = sm.poll_for_reply(correlation_id)
        latency_ms = int((time.time() - start) * 1000)

        if reply is None:
            return {
                "success": False,
                "error": f"Timeout waiting for Snackmachine reply (correlation_id: {correlation_id})",
                "peer": peer_id,
                "latency_ms": latency_ms,
            }

        return {
            "success": reply.get("status") == "success",
            "result": {
                "output": reply.get("output", ""),
                "error": reply.get("error", ""),
                "status": reply.get("status", "unknown"),
            },
            "peer": peer_id,
            "latency_ms": latency_ms,
        }

    async def _call_tool_http(self, peer_id: str, tool: str, params: dict = None) -> dict:
        """Call a tool via HTTP on a remote Snackbar."""
        peer = self.peers.get(peer_id)
        if not peer:
            return {"success": False, "error": f"Unknown peer: {peer_id}"}

        if peer["status"] == "offline":
            health = await self.check_peer_health(peer_id)
            if health["status"] != "online":
                return {"success": False, "error": f"Peer {peer_id} is offline"}

        endpoint = peer["endpoint"]
        payload = {"tool": tool, "params": params or {}}

        try:
            session = await self._get_session()
            start = time.time()
            async with session.post(
                urljoin(endpoint + "/", "v1/mcp/call"),
                json=payload,
                timeout=self._timeout,
            ) as resp:
                latency_ms = int((time.time() - start) * 1000)
                if resp.status == 200:
                    result = await resp.json()
                    return {
                        "success": True,
                        "result": result.get("result", result),
                        "peer": peer_id,
                        "latency_ms": latency_ms,
                    }
                else:
                    error_text = await resp.text()
                    return {
                        "success": False,
                        "error": f"Remote error (HTTP {resp.status}): {error_text}",
                        "peer": peer_id,
                        "latency_ms": latency_ms,
                    }
        except Exception as e:
            self.peers[peer_id]["status"] = "offline"
            return {
                "success": False,
                "error": str(e),
                "peer": peer_id,
            }

    async def list_remote_tools(self, peer_id: str) -> dict:
        """List all MCP tools available on a remote peer.

        Uses the appropriate transport:
          - HTTP:        GET /v1/mcp/tools on the remote endpoint
          - snackmachine: Read available spices/skills from the spool
        """
        peer = self.peers.get(peer_id)
        if not peer:
            return {"success": False, "error": f"Unknown peer: {peer_id}"}

        transport = peer.get("transport", "http")

        # ── Snackmachine file-based listing ──
        if transport == "snackmachine":
            sm = self._get_snackmachine_transport(peer_id)
            if not sm:
                return {"success": False, "error": f"No Snackmachine transport for peer: {peer_id}"}

            available = sm.list_available()
            tools = []

            for spice in available.get("spices", []):
                tools.append({
                    "name": f"spice:{spice}",
                    "description": f"Snackmachine spice: {spice}",
                    "server": peer_id,
                })
            for skill in available.get("skills", []):
                tools.append({
                    "name": f"skill:{skill}",
                    "description": f"Snackmachine skill: {skill}",
                    "server": peer_id,
                })

            return {
                "success": True,
                "peer": peer_id,
                "tools": tools,
            }

        # ── HTTP transport ──
        endpoint = peer["endpoint"]
        try:
            session = await self._get_session()
            async with session.get(
                urljoin(endpoint + "/", "v1/mcp/tools"),
                timeout=self._timeout,
            ) as resp:
                if resp.status == 200:
                    tools = await resp.json()
                    return {
                        "success": True,
                        "peer": peer_id,
                        "tools": tools.get("tools", tools),
                    }
                else:
                    return {
                        "success": False,
                        "error": f"HTTP {resp.status}",
                        "peer": peer_id,
                    }
        except Exception as e:
            return {
                "success": False,
                "error": str(e),
                "peer": peer_id,
            }

    async def get_mesh_tools(self) -> dict:
        """Aggregate MCP tools from all online peers."""
        local_tools = []
        remote_tools = []

        for peer_id, peer in self.peers.items():
            if peer["status"] != "online":
                continue
            result = await self.list_remote_tools(peer_id)
            if result.get("success"):
                tools = result.get("tools", [])
                for tool in tools:
                    entry = {
                        "name": tool.get("name", tool) if isinstance(tool, str) else tool,
                        "server": peer_id,
                        "enabled": True,
                    }
                    if peer_id == "wizard" or peer_id == "localhost":
                        local_tools.append(entry)
                    else:
                        remote_tools.append(entry)

        return {
            "local": local_tools,
            "remote": remote_tools,
            "total": len(local_tools) + len(remote_tools),
        }

    # ── Remote Skill Execution ──────────────────────────────────────

    async def run_skill(self, peer_id: str, skill_id: str, params: dict = None) -> dict:
        """Run a skill on a remote peer.

        Uses the appropriate transport:
          - HTTP:        POST /v1/skills/{id}/run on the remote endpoint
          - snackmachine: Write run_skill command to JSONL queue, poll for reply
        """
        peer = self.peers.get(peer_id)
        if not peer:
            return {"success": False, "error": f"Unknown peer: {peer_id}"}

        transport = peer.get("transport", "http")

        # ── Snackmachine file-based transport ──
        if transport == "snackmachine":
            sm = self._get_snackmachine_transport(peer_id)
            if not sm:
                return {"success": False, "error": f"No Snackmachine transport for peer: {peer_id}"}

            if not sm.check_health():
                self.peers[peer_id]["status"] = "offline"
                return {"success": False, "error": f"Peer {peer_id} is offline"}

            self.peers[peer_id]["status"] = "online"
            start = time.time()

            cmd = {
                "type": "run_skill",
                "name": skill_id,
                "params": params or {},
            }
            correlation_id = sm.write_command(cmd)
            reply = sm.poll_for_reply(correlation_id)
            duration_ms = int((time.time() - start) * 1000)

            if reply is None:
                return {
                    "success": False,
                    "error": f"Timeout waiting for Snackmachine reply",
                    "peer": peer_id,
                    "duration_ms": duration_ms,
                }

            return {
                "success": reply.get("status") == "success",
                "output": reply.get("output", ""),
                "error": reply.get("error", ""),
                "peer": peer_id,
                "duration_ms": duration_ms,
            }

        # ── HTTP transport ──
        if peer["status"] == "offline":
            health = await self.check_peer_health(peer_id)
            if health["status"] != "online":
                return {"success": False, "error": f"Peer {peer_id} is offline"}

        endpoint = peer["endpoint"]
        payload = {"params": params or {}}

        try:
            session = await self._get_session()
            start = time.time()
            async with session.post(
                urljoin(endpoint + "/", f"v1/skills/{skill_id}/run"),
                json=payload,
                timeout=self._timeout,
            ) as resp:
                duration_ms = int((time.time() - start) * 1000)
                if resp.status == 200:
                    result = await resp.json()
                    return {
                        "success": True,
                        "output": result.get("output", result),
                        "peer": peer_id,
                        "duration_ms": duration_ms,
                    }
                else:
                    error_text = await resp.text()
                    return {
                        "success": False,
                        "error": f"Remote error (HTTP {resp.status}): {error_text}",
                        "peer": peer_id,
                        "duration_ms": duration_ms,
                    }
        except Exception as e:
            self.peers[peer_id]["status"] = "offline"
            return {
                "success": False,
                "error": str(e),
                "peer": peer_id,
            }

    # ── Mesh Status ─────────────────────────────────────────────────



    async def get_mesh_status(self) -> dict:
        """Get full mesh status including peer health and tool counts."""
        peer_health = await self.check_all_peers()
        mesh_tools = await self.get_mesh_tools()

        online_count = sum(1 for p in peer_health if p["status"] == "online")
        offline_count = sum(1 for p in peer_health if p["status"] == "offline")

        return {
            "peers": peer_health,
            "tools": mesh_tools,
            "summary": {
                "total_peers": len(peer_health),
                "online": online_count,
                "offline": offline_count,
                "total_tools": mesh_tools["total"],
            },
        }


# ─── Singleton ──────────────────────────────────────────────────────

_bridge_instance: Optional[MCPBridge] = None


def get_bridge() -> MCPBridge:
    """Get or create the singleton MCPBridge instance."""
    global _bridge_instance
    if _bridge_instance is None:
        _bridge_instance = MCPBridge()
    return _bridge_instance

