from __future__ import annotations

"""skills module — extracted from mcp_bridge.py"""
# Auto-generated by file-splitter on 20260618_215801

"""
MCP Bridge — Cross-Machine Tool & Skill Execution
==================================================
Proxies MCP tool calls and skill execution to remote peers (e.g., Forge).

Architecture:
    Wizard MCP Client
           │
           ▼
    Wizard Snackbar (/v1/mcp/bridge/call)
           │
           ├── Local MCP tools (direct)
           │
           └── Forge Snackmachine (file-based JSONL queue)
                     │
                     └── Forge local execution (spices/skills)

Transport backends:
  - HTTP:   POST /v1/mcp/call on remote Snackbar (for future HTTP peers)
  - File:   JSONL queue → Snackmachine commands.jsonl → replies.jsonl
  - SSH:    (future) direct SSH command execution

Usage:
    from mcp_bridge import MCPBridge
    bridge = MCPBridge()
    result = await bridge.call_tool("forge", "copernicus.search", {"query": "test"})
"""


import json
import time
import os
import uuid
import logging
from pathlib import Path
from typing import Optional
from urllib.parse import urljoin

try:
    from aiohttp import ClientSession, ClientTimeout
except ImportError:
    ClientSession = None
    ClientTimeout = None



    async def run_skill(self, peer_id: str, skill_id: str, params: dict = None) -> dict:
        """Run a skill on a remote peer.

        Uses the appropriate transport:
          - HTTP:        POST /v1/skills/{id}/run on the remote endpoint
          - snackmachine: Write run_skill command to JSONL queue, poll for reply
        """
        peer = self.peers.get(peer_id)
        if not peer:
            return {"success": False, "error": f"Unknown peer: {peer_id}"}

        transport = peer.get("transport", "http")

        # ── Snackmachine file-based transport ──
        if transport == "snackmachine":
            sm = self._get_snackmachine_transport(peer_id)
            if not sm:
                return {"success": False, "error": f"No Snackmachine transport for peer: {peer_id}"}

            if not sm.check_health():
                self.peers[peer_id]["status"] = "offline"
                return {"success": False, "error": f"Peer {peer_id} is offline"}

            self.peers[peer_id]["status"] = "online"
            start = time.time()

            cmd = {
                "type": "run_skill",
                "name": skill_id,
                "params": params or {},
            }
            correlation_id = sm.write_command(cmd)
            reply = sm.poll_for_reply(correlation_id)
            duration_ms = int((time.time() - start) * 1000)

            if reply is None:
                return {
                    "success": False,
                    "error": f"Timeout waiting for Snackmachine reply",
                    "peer": peer_id,
                    "duration_ms": duration_ms,
                }

            return {
                "success": reply.get("status") == "success",
                "output": reply.get("output", ""),
                "error": reply.get("error", ""),
                "peer": peer_id,
                "duration_ms": duration_ms,
            }

        # ── HTTP transport ──
        if peer["status"] == "offline":
            health = await self.check_peer_health(peer_id)
            if health["status"] != "online":
                return {"success": False, "error": f"Peer {peer_id} is offline"}

        endpoint = peer["endpoint"]
        payload = {"params": params or {}}

        try:
            session = await self._get_session()
            start = time.time()
            async with session.post(
                urljoin(endpoint + "/", f"v1/skills/{skill_id}/run"),
                json=payload,
                timeout=self._timeout,
            ) as resp:
                duration_ms = int((time.time() - start) * 1000)
                if resp.status == 200:
                    result = await resp.json()
                    return {
                        "success": True,
                        "output": result.get("output", result),
                        "peer": peer_id,
                        "duration_ms": duration_ms,
                    }
                else:
                    error_text = await resp.text()
                    return {
                        "success": False,
                        "error": f"Remote error (HTTP {resp.status}): {error_text}",
                        "peer": peer_id,
                        "duration_ms": duration_ms,
                    }
        except Exception as e:
            self.peers[peer_id]["status"] = "offline"
            return {
                "success": False,
                "error": str(e),
                "peer": peer_id,
            }

    # ── Mesh Status ─────────────────────────────────────────────────

    async def get_mesh_status(self) -> dict:
        """Get full mesh status including peer health and tool counts."""
        peer_health = await self.check_all_peers()
        mesh_tools = await self.get_mesh_tools()

        online_count = sum(1 for p in peer_health if p["status"] == "online")
        offline_count = sum(1 for p in peer_health if p["status"] == "offline")

        return {
            "peers": peer_health,
            "tools": mesh_tools,
            "summary": {
                "total_peers": len(peer_health),
                "online": online_count,
                "offline": offline_count,
                "total_tools": mesh_tools["total"],
            },
        }


# ─── Singleton ──────────────────────────────────────────────────────

_bridge_instance: Optional[MCPBridge] = None


def get_bridge() -> MCPBridge:
    """Get or create the singleton MCPBridge instance."""
    global _bridge_instance
    if _bridge_instance is None:
        _bridge_instance = MCPBridge()
    return _bridge_instance

