import React, { useState, useEffect, useRef, useCallback } from 'react';
import { shortcodeToSVG, shortcodeToUnicode } from '@/shared/symbols/registry';

/**
 * InlineBob — uVector-powered inline sprite/icon component for ProseUI.
 *
 * Renders a small SVG bob (16×16 or 32×32) generated by uVector from a
 * text prompt, SVG source, or shortcode. Supports mono_chrome, teletext,
 * and full-color palettes.
 *
 * Usage:
 *   <InlineBob shortcode=":heart:" />
 *   <InlineBob shortcode=":rocket:" size="32x32" />
 *   <InlineBob prompt="heart icon" style="mono_chrome" size="16x16" />
 *   <InlineBob src="/path/to/icon.svg" size="32x32" />
 *
 * The component caches generated bobs in the Vault and falls back to
 * a placeholder if uVector is unavailable.
 */

export type BobStyle = 'mono_chrome' | 'teletext' | 'full_color';
export type BobSize = '16x16' | '32x32';

export interface InlineBobProps {
  /** Shortcode to resolve (e.g. ":heart:", ":rocket:") */
  shortcode?: string;
  /** Text prompt for uVector generation (alternative to src/shortcode) */
  prompt?: string;
  /** Direct SVG source URL or path */
  src?: string;
  /** Visual style */
  style?: BobStyle;
  /** Output size */
  size?: BobSize;
  /** CSS class name override */
  className?: string;
  /** Alt text for accessibility */
  alt?: string;
}

const BOB_CACHE = new Map<string, string>();

function generateCacheKey(prompt: string, style: BobStyle, size: BobSize): string {
  return `bob:${prompt}:${style}:${size}`;
}

async function generateBob(
  prompt: string,
  style: BobStyle,
  size: BobSize
): Promise<string | null> {
  const cacheKey = generateCacheKey(prompt, style, size);
  const cached = BOB_CACHE.get(cacheKey);
  if (cached) return cached;

  try {
    // Call uVector SVG generation via Snackbar API
    const [w, h] = size.split('x').map(Number);
    const response = await fetch('http://localhost:8484/api/svg/generate', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        prompt,
        style: style === 'mono_chrome' ? 'mono_chrome' : style === 'teletext' ? 'teletext' : 'full_color',
        width: w * 4,
        height: h * 4,
        background: false,
        extra: 'Generate a simple icon/symbol. Use minimal elements. Keep it clean and recognizable.',
      }),
    });

    if (response.ok) {
      const data = await response.json();
      const svg = data.svg;
      if (svg) {
        // Convert SVG to data URL
        const encoded = btoa(unescape(encodeURIComponent(svg)));
        const dataUrl = `data:image/svg+xml;base64,${encoded}`;
        BOB_CACHE.set(cacheKey, dataUrl);
        return dataUrl;
      }
    }
  } catch {
    // uVector not available — fall through to placeholder
  }

  return null;
}

/**
 * Generate a simple inline SVG placeholder based on the prompt text.
 * This provides a visual fallback when uVector is unavailable.
 */
function generatePlaceholderSVG(prompt: string, style: BobStyle, size: BobSize): string {
  const [w, h] = size.split('x').map(Number);
  const isMono = style === 'mono_chrome';
  const isTeletext = style === 'teletext';
  const fill = isMono ? '#000' : isTeletext ? '#ff0' : '#6366f1';
  const bg = isMono ? '#fff' : isTeletext ? '#000' : '#f0f0ff';
  const label = prompt.slice(0, 2).toUpperCase();

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}">
    <rect width="${w}" height="${h}" fill="${bg}" rx="2"/>
    <text x="${w/2}" y="${h/2 + 4}" text-anchor="middle" font-size="10" fill="${fill}" font-family="monospace">${label}</text>
  </svg>`;
}

export const InlineBob: React.FC<InlineBobProps> = ({
  shortcode,
  prompt,
  src,
  style = 'mono_chrome',
  size = '16x16',
  className,
  alt,
}) => {
  const [svgDataUrl, setSvgDataUrl] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [showDownload, setShowDownload] = useState(false);
  const mountedRef = useRef(true);

  useEffect(() => {
    return () => {
      mountedRef.current = false;
    };
  }, []);

  useEffect(() => {
    let cancelled = false;

    async function load() {
      setLoading(true);

      // Priority: shortcode > src > prompt
      if (shortcode) {
        // Resolve from symbol registry
        const svg = shortcodeToSVG(shortcode);
        if (svg) {
          const encoded = btoa(svg);
          setSvgDataUrl(`data:image/svg+xml;base64,${encoded}`);
          setLoading(false);
          return;
        }
        // Fallback: use unicode character
        const unicode = shortcodeToUnicode(shortcode);
        if (unicode && unicode !== shortcode) {
          const [w, h] = size.split('x').map(Number);
          const placeholder = `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}">
            <text x="${w/2}" y="${h - 2}" text-anchor="middle" font-size="14">${unicode}</text>
          </svg>`;
          const encoded = btoa(placeholder);
          setSvgDataUrl(`data:image/svg+xml;base64,${encoded}`);
          setLoading(false);
          return;
        }
      }

      if (src) {
        // Direct source — use as-is
        setSvgDataUrl(src);
        setLoading(false);
        return;
      }

      if (prompt) {
        // Try uVector generation
        const generated = await generateBob(prompt, style, size);
        if (cancelled || !mountedRef.current) return;

        if (generated) {
          setSvgDataUrl(generated);
        } else {
          // Fallback to placeholder
          const placeholder = generatePlaceholderSVG(prompt, style, size);
          const encoded = btoa(placeholder);
          setSvgDataUrl(`data:image/svg+xml;base64,${encoded}`);
        }
      }

      setLoading(false);
    }

    load();
    return () => { cancelled = true; };
  }, [shortcode, prompt, src, style, size]);

  const [w, h] = size.split('x').map(Number);

  /* ── Download bob as SVG ── */
  const downloadSvg = useCallback(() => {
    if (!svgDataUrl) return
    const a = document.createElement('a')
    a.href = svgDataUrl
    a.download = `bob-${(shortcode || prompt || 'icon').replace(/[^a-z0-9]/gi, '-').toLowerCase()}.svg`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
  }, [svgDataUrl, shortcode, prompt])

  /* ── Download bob as PNG ── */
  const downloadPng = useCallback(() => {
    if (!svgDataUrl) return
    const img = new Image()
    img.onload = () => {
      const canvas = document.createElement('canvas')
      canvas.width = w * 4
      canvas.height = h * 4
      const ctx = canvas.getContext('2d')
      if (!ctx) return
      ctx.imageSmoothingEnabled = false
      ctx.drawImage(img, 0, 0, canvas.width, canvas.height)
      canvas.toBlob(blob => {
        if (!blob) return
        const url = URL.createObjectURL(blob)
        const a = document.createElement('a')
        a.href = url
        a.download = `bob-${(shortcode || prompt || 'icon').replace(/[^a-z0-9]/gi, '-').toLowerCase()}.png`
        document.body.appendChild(a)
        a.click()
        document.body.removeChild(a)
        URL.revokeObjectURL(url)
      }, 'image/png')
    }
    img.src = svgDataUrl
  }, [svgDataUrl, w, h, shortcode, prompt])

  return (
    <span
      className={`inline-bob ${className || ''}`}
      style={{
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        width: w,
        height: h,
        verticalAlign: 'middle',
        margin: '0 2px',
        position: 'relative',
      }}
      title={alt || shortcode || prompt || 'inline bob'}
      onMouseEnter={() => setShowDownload(true)}
      onMouseLeave={() => setShowDownload(false)}
    >
      {loading ? (
        <span
          style={{
            display: 'inline-block',
            width: w,
            height: h,
            background: 'var(--bob-loading-bg, #e5e7eb)',
            borderRadius: 2,
            animation: 'pulse 1.5s ease-in-out infinite',
          }}
        />
      ) : svgDataUrl ? (
        <img
          src={svgDataUrl}
          alt={alt || shortcode || prompt || 'bob'}
          style={{
            width: w,
            height: h,
            imageRendering: style === 'teletext' ? 'pixelated' : 'auto',
          }}
        />
      ) : null}
      {/* Download buttons on hover */}
      {showDownload && svgDataUrl && (
        <span
          style={{
            position: 'absolute',
            top: -20,
            right: -4,
            display: 'flex',
            gap: 2,
            zIndex: 50,
          }}
        >
          <button
            onClick={e => { e.stopPropagation(); downloadSvg() }}
            title="Download as SVG"
            style={{
              width: 18,
              height: 18,
              fontSize: 10,
              lineHeight: '18px',
              textAlign: 'center',
              background: 'var(--m3-surface-container-high, #e5e7eb)',
              border: '1px solid var(--m3-outline, #d1d5db)',
              borderRadius: 3,
              cursor: 'pointer',
              padding: 0,
              color: 'var(--m3-on-surface, #111827)',
            }}
          >
            SVG
          </button>
          <button
            onClick={e => { e.stopPropagation(); downloadPng() }}
            title="Download as PNG"
            style={{
              width: 18,
              height: 18,
              fontSize: 10,
              lineHeight: '18px',
              textAlign: 'center',
              background: 'var(--m3-surface-container-high, #e5e7eb)',
              border: '1px solid var(--m3-outline, #d1d5db)',
              borderRadius: 3,
              cursor: 'pointer',
              padding: 0,
              color: 'var(--m3-on-surface, #111827)',
            }}
          >
            PNG
          </button>
        </span>
      )}
    </span>
  );
};

export default InlineBob;
