// TeletextPanel — slim entry point (modules split by file-splitter)
// Auto-generated by file-splitter on 20260618_220138



export * from "./TeletextPanel_other";  // other

// Original file backed up to:
//   /Users/fredbook/.snackbar/backups/file-splitter/20260618_220138_TeletextPanel.tsx