// UIHubManager — slim entry point (modules split by file-splitter)
// Auto-generated by file-splitter on 20260618_220117



export * from "./UIHubManager_surfaces";  // surfaces
export * from "./UIHubManager_other";  // other
export { default } from "./UIHubManager_other";  // re-export default (UIHubManager)

// Original file backed up to:
//   /Users/fredbook/.snackbar/backups/file-splitter/20260618_220117_UIHubManager.tsx